### ISSUE TITLE
Remove category rows from FCT tables

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/fct#2]
Several of the FCTs contain rows that indicate categories. Ideally, we want to avoid rows like that. Every row should be an instance of a fooditem, and every column should be an attribute of that fooditem.

**Comment by LuciaSegovia** [comment]
Hi there!

This, I have fixed already :) for those FCT that we are going to use (for now).

Lucia

**Comment by rbroth** [comment]
Excellent, I'll close this issue then
