### ISSUE TITLE
Fix text encoding

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/fct#3]
The file MAPS_WAFCT has several text encoding errors. For example, food item 1 (code 01_172) has the following name: `Baling bÃ©inrÃ© (northern Burkina Faso)*: sorghum porridge with monkey bread, tamarind, water, milk and sugar`. Since it is unlikely that Burkina Fasoans use the copyright symbol in their food names, there must have been an error in converting the original FCT data into csv

**Comment by LuciaSegovia** [comment]
Hi Roman! 

I've just seen this! Yeah, I know what you mean. I need to google how to fix that. 👍

**Comment by rbroth** [comment]
I'm quite busy on other project for the next few weeks, but I might be able to have  a look at some point. See if you can identify the source of the problem; does the encoding problem exist in the source document? Or does it get introduced at some point during processing?

**Comment by LuciaSegovia** [comment]
No problem! It was introduced when saving it on csv and excel compatibility. It's sorted now :) 

Closing this issue!
